# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_resturant_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resturant',
            new_name='ResturantLocation',
        ),
    ]
