# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180103_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
