# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180103_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResturantLocation',
            new_name='RestaurantLocation',
        ),
    ]
