# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 08:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantlocation_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantlocation',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
