# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20180108_0857'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurantlocation',
            managers=[
            ],
        ),
    ]
