# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180108_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fallowing',
        ),
    ]
