# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_remove_profile_fallowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fallowers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
